version: '2'

services:

### Applications Code Container #############################

    db-applications:
      image: tianon/true
      volumes:
        - ./:/var/www

### Workspace Utilities Container ###########################
    db-php-fpm:
      container_name: "${CONTAINER_NAME_PREFIX}-php-fpm"
      build:
        context: ./laradock/php-fpm
        args:
          - INSTALL_XDEBUG=false
          - INSTALL_BLACKFIRE=false
          - INSTALL_SOAP=false
          - INSTALL_MONGO=false
          - INSTALL_MSSQL=false
          - INSTALL_BCMATH=false
          - INSTALL_ZIP_ARCHIVE=false
          - INSTALL_PHPREDIS=false
          - INSTALL_MEMCACHED=false
          - INSTALL_OPCACHE=false
          - INSTALL_EXIF=false
          - INSTALL_AEROSPIKE=false
          - INSTALL_MYSQLI=true
          - INSTALL_TOKENIZER=false
          - INSTALL_INTL=false
          - INSTALL_GHOSTSCRIPT=fale
          - INSTALL_LDAP=false
          - INSTALL_SWOOLE=false
          - INSTALL_IMAGE_OPTIMIZERS=false
          - INSTALL_IMAGEMAGICK=false
        dockerfile: "Dockerfile-71"
      volumes_from:
        - db-applications
      volumes:
        - ./php-fpm/php71.ini:/usr/local/etc/php/php.ini
      expose:
        - 9000
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      environment:
        - PHP_IDE_CONFIG=serverName=laradock
      networks:
        - backend


    db-mariadb:
      container_name: "${CONTAINER_NAME_PREFIX}-mariadb"
      build: ./laradock/mariadb
      volumes:
        - ${DATA_SAVE_PATH}/mariadb:/var/lib/mysql
        - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MARIADB_PORT}:3306"
      environment:
        - MYSQL_DATABASE=${MARIADB_DATABASE}
        - MYSQL_USER=${MARIADB_USER}
        - MYSQL_PASSWORD=${MARIADB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      networks:
        - backend


### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################

